models and migrations
sagranja/chx pull request #5
Opened 2019-03-16 22:31 UTC by tigersabre

Hi guys, decided to redo the pull request and limit to just the model changes.  Please review and approve :)

2019-03-16 22:55 UTC, AnnessaBW requested changes
@tigersabre Thank you! Would you please move the .idea files to .gitignore? I think we will be good to go from there :)

2019-03-17 18:53 UTC, tigersabre commented
I have it in another PR that was just merged, will that be ok?

2019-03-18 23:37 UTC, grel4d commented
I do not mind changing my model around so there aren't redundancies because there is some overlap.

2019-03-19 02:27 UTC, AnnessaBW approved these changes

2019-03-21 15:36 UTC, merged